### ISSUE TITLE
[Feature Request] Parameter to split <project> to multiple lines

### ISSUE THREAD

**Issue by bpt6576** [Ekryd/sortpom#36]
The <project> element with xmlns, xsi, etc., currently is reformatted to all be on one line.

I would like it split onto four lines so that each line is no more than 80 characters.

My team uses Atlassian Crucible for code reviews. It displays the old code side-by-side with the new code. A lot of our pom.xml files don't have any lines longer than 100 characters, except for the <project> line which is formatted onto one line of over 200 characters. This causes a very big horizontal scroll bar between the old and new code which is just empty space, difficult to compare changes.

I'm not asking to enforce 80 character line limits, just allow the <project> line to be formatted to something shorter than over 200 characters on one line.

**Comment by Ekryd** [comment]
Interesting problem, but hard to do. 
The SortPom plugin relies on a library called JDom 1.1.3 and it is that library that formats the xml in the end. The plugin overrides some of the formatting methods in that libray, but I have to follow the existing method signatures. 
I had a look inside and there were two obvious problems: 1. the library has no concept of lines or characters, it just writes to an output stream; 2. the printAttributes method does not keep track of level. This means that a line can only be split after a certain number of attributes, i.e. after 6 attributes you get a new line regardless of length, and the split line will not follow the current line indent.

Could you send me an example of your pom-file, so that I can see if the problem can be solved in another way?

**Comment by bpt6576** [comment]
We found a line wrapping setting in the code review tool so this is no longer an issue for us. An example of what was causing us problems is this pom-file here
http://maven.apache.org/pom.html#Quick_Overview
Lines one through four of the project XML element are being formatted into a single, long line.

**Comment by Ekryd** [comment]
Ok, it was the fist line in the pom-file. That would make it harder ignore sections. Anyway I am glad that you found a solution.
