### ISSUE TITLE
Add configuration to suppress XML declaration

### ISSUE THREAD

**Issue by zabetak** [Ekryd/sortpom#398]
Currently the plugin enforces the XML declaration (`<?xml version="1.0" encoding="UTF-8"?>`) to be present in the pom.xml file so if it is not there it will be added during the sort phase. There are many pom.xml files that don't contain the XML declaration, which is also optional in some versions of XML, so it makes sense to be able to suppress it.

The presence of the XML declaration can be controlled via [OutputFormat.setSuppressDeclaration](https://github.com/dom4j/dom4j/blob/41b079a88790b8d5694aa6c9c738dd624a0a667b/src/main/java/org/dom4j/io/OutputFormat.java#L218).

**Comment by zabetak** [comment]
Other XML processing plugins may opt to add/remove the XML declaration as well. If each plugin does something different then combining them in the same build becomes cumbersome since they contradict each other.

In the project where I am trying to apply the sortPom plugin there is another one in place which is processing the file and does some XML replacement logic. Among other things the other plugin removes the XML declaration if there is one.

**Comment by Ekryd** [comment]
Would it be reasonable that, in general: 
* omit creating a new xml declaration if it didn't exist in the first place
* keep the xml declaration if it exist

I'm a bit hesitant to add new parameters for adding/removing xml declarations.

**Comment by zabetak** [comment]
For me its perfectly fine to say that the plugin does not bother at all with the XML declaration.

The parameter would be useful to retain backward compatibility since currently the plugin will add the XML declaration if its missing. Other than that I don't feel strongly about it.

**Comment by Stephan202** [comment]
Not that I have a strong opinion here, but a key aim of this plugin seems to be to ensure consistency. Given a team setup in which developers create new `pom.xml` files using different tools (which may include or omit the XML declaration), it seems to me that ensuring consistency in this respect requires either exposing a flag, or unconditionally doing one or the other. (In the latter case I'd expect the plugin to _add_ the XML declaration, as the [specification](https://www.w3.org/TR/xml/#sec-prolog-dtd) states that it SHOULD be added.)

Of course one could also state that the plugin should indeed not touch this aspect of the `pom.xml` file, since it has nothing to do with _sorting_. :upside_down_face:

**Comment by zabetak** [comment]
The reason I opened this ticket is cause I couldn't find a way to stop the other plugin (let's call it PX) from removing the XML declaration without code changes on PX itself. Same goes for sortpom; I couldn't find a way to stop it from adding the XML declaration.

In parallel, I am trying to make the PX respect the XML declaration if its there. Nevertheless, addressing this issue here can probably remove this small adoption blocker for sortpom as well.

**Comment by Ekryd** [comment]
First of all, I appreciate all the options on this.

Did some experiments and there doesn't seem to be a good way to detect the presence of XML declaration through methods in the `Document` class, after it has been parsed by `org.dom4j.io.SAXReader`. So a solution to leave the XML declaration unchanged automatically does not seem to be an option.

I'm a bit hesitant to add another parameter to the existing ~24 ones, especially since it only concerns xml formatting and not Maven structure formatting (which is the plugins main focus).

@zabetak It sounds like the problem you have with the other tool is temporary, would a solution be to clone SortPom for now and implement this functionally locally?
