### ISSUE TITLE
Show line number

### ISSUE THREAD

**Issue by php-coder** [Ekryd/sortpom#45]
I'd like to see on which line I have an error. At present, plugin shows only a message:

```console
$ mvn sortpom:verify -Dsort.verifyFail=stop
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building My Stamps 0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- sortpom-maven-plugin:2.5.0:verify (default-cli) @ mystamps ---
[INFO] Verifying file /Users/coder/git/mystamps.git/pom.xml
[ERROR] The xml element <groupId>com.github.heneke.thymeleaf</groupId> should be placed before <groupId>javax.validation</groupId>
[ERROR] The file /Users/coder/git/mystamps.git/pom.xml is not sorted
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by Ekryd** [comment]
I use a library called Jdom to parse the XML, and I think that this library doesn't support the concept of line numbers. I look into this further, but the chances are slim.

**Comment by Ekryd** [comment]
The plugin works like this for verification:
1. The pom.xml is parsed by the JDOM library into an element structure. That library does not store the line numbers for the elements.
2. The plugin sorts the element structure
3. The plugin traverses both the original element structure and the sorted element structure. For each pair of elements the plugin checks if the elements and the content are the same.
4. When the two elements differ, the plugin writes an error message.

The problem is that the element structure does not have access to the line number. I could try to locate the elements in the original file by using a line by line string comparison, but I cannot be certain that I get a unique match or even that I get a match at all (if element start or end is on separate lines). 

Sometimes the line number indication would point to the wrong line and sometimes it would be missing.
Would it help you to get a line number that you could not trust?

**Comment by php-coder** [comment]
I'm surprised that library didn't have information about line numbers. Is it something JDOM-specific or all the libraries have the same behavior?

**Comment by Ekryd** [comment]
It is JDOM specific. It is an old library (think Java 1.4) and I don't have the time to change xml parsing library. Some of the plugin functionality is now directly dependent on that version of that library. 
Not very good design and I can only say that I would have done differently today than in 2009 :-/

**Comment by php-coder** [comment]
Why not keep this issue open to be able to fix it someday in the next major release?

**Comment by Ekryd** [comment]
Sorry mate, it won't happen. I don't have time to rewrite the plugin from scratch. It is no idea to keep issues open if I can't fix them within reasonable time.

**Comment by khmarbaise** [comment]
But others could see what can be done and might offer a pull request...

**Comment by Ekryd** [comment]
To rewrite the plugin from scratch :-D
I'm not even sure that I would like that (it's my baby!!).

How about if I create a wiki page that collects issues (epics) that can only be done sometime in the future?

**Comment by khmarbaise** [comment]
Sorry to say, but if you don't like it than do not make it open source ;-( But of course a wiki pages which collects issues like this would be another good idea...

**Comment by php-coder** [comment]
>Sorry to say, but if you don't like it than do not make it open source ;-(

@Ekryd did a good job by creating this plugin and it's ok that he doesn't want to accept some PRs because of some reason. Actually it's good that he said it as-is right now. It just means that if someone wants to implement it, he/she should fork this project instead of creating a PR here.

**Comment by khmarbaise** [comment]
Of course a fork is also a reasonable solution.
