### ISSUE TITLE
Optionally extract version numbers from dependencies (GAV-blocks) to version properties in pom

### ISSUE THREAD

**Issue by TomBenjamins** [Ekryd/sortpom#461]
I like your plugin a lot, but feel there is only one bit missing in the way I like to format pom.xml

Is it perhaps possible to add the following optional setting to the configuration?

`<configuration>
              <createBackupFile>true</createBackupFile>  
              <predefinedSortOrder>custom_1</predefinedSortOrder>  
              <lineSeparator>\n</lineSeparator>  
              <sortProperties>true</sortProperties>  
              <sortDependencies>scope,groupId,artifactId</sortDependencies>  
	     <nrOfIndentSpace>4</nrOfIndentSpace>  
             <extractVersionNumbersToProperties>true</extractVersionNumbersToProperties> 			  
</configuration>`

which will make the following dependency

 `<dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.23</version>
        </dependency>`

into

the property
`<swagger-annotations.version>1.5.23</swagger-annotations.version>`
and GAV block:
        `<dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger-annotations.version}</version>
        `</dependency>

I would really appreciate your opinion on this proposed feature, and if I am able to help in any way, please let me know,

greetings,

Tom Benjamins

**Comment by Ekryd** [comment]
I think I know what you mean; extracting all the version numbers of dependencies and plugins into the properties section of the pom file.

This is not within the scope of the plugin itself. SortPom is all about sorting and formatting the pom, and not about refactoring. I would suggest that you create your own Maven plugin for it. 
You can use SortPom as template (but perhaps keeping everything in one Maven module instead of splitting it into several modules). It is actually not that hard and I'll be happy to give you tips and tricks.

I have always wondered why you would extract the version numbers. There must be some guidance that I have missed. Do you have some link to a good article about version placements? (I have seen that Gradle projects use this a lot and even as a separate file)

**Comment by TomBenjamins** [comment]
Hello Björn,

I'm still thinking about it, but it could also be a Open Rewite Script, depending on what takes less time to implement.

greetings, Tom

________________________________
