### ISSUE TITLE
Keep consecutive blank lines

### ISSUE THREAD

**Issue by camshoff** [Ekryd/sortpom#52]
In bigger POM files, we use to have several blank lines to separate sections from one another. However, even when passing option `-Dsort.keepBlankLines=true`, there is only one of them preserved.

How about adding another option like `nrOfBlankLinesToKeep` to let the user specify how many blank lines should be kept? For instance if this is set to 2, at most two consecutive blank lines of the source file are preserved and remaining ones are removed it there are more than that.

BTW, great plugin!

**Comment by Ekryd** [comment]
Ok. I will look into this as soon as I am able

**Comment by Ekryd** [comment]
Once again the underlying JDOM library sets the difficulty. JDOM treats all characters (including multiple lines) between xml tags as text.
Technically I detect if the line or lines contains multiple newlines (one to terminate the line above and others to create one or more lines), and this will be represented as one special element for the blank line(s). This special element will then generate one blank line with JDOM.

So your problem can be solved by detecting the number of blank lines (quite easy) in the TextWrapperCreator class. But it will be harder to patch the JDOM to output multiple lines from one element in the XmlOutputGenerator.PatchedXMLOutputter class, since it just generates one line per element.

I recognise your original problem and I also separate sections for large pom-files, but with a xml comments instead. So my question to you is if you can solve your problem by using xml comments instead of multiple blank lines?
```
Example from my own pom-file
...
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>2.2</version>
        </plugin>

        <!-- Release management -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>2.5.1</version>
          <configuration>
            <autoVersionSubmodules>true</autoVersionSubmodules>
            <useReleaseProfile>false</useReleaseProfile>
            <arguments>-Pdistribution</arguments>
            <goals>deploy</goals>
          </configuration>
        </plugin>

        <!-- References plugins (not directly used) -->
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>1.8</version>
        </plugin>
...
```

**Comment by camshoff** [comment]
Thanks for looking into this.  I'm sorry such simple looking task turns out to be quite complicated...

Well, of course we are using comments already on some tags or blocks of tags in the POM. However, there are POMs (mostly base POMs) which are getting quite large (1000 lines and more) due to configuration of lots of dependencies, plugins and profiles. In this case I like to use multiple blank lines to better separate sections.

So I'd still love to see this option, but if it's technically impossible or just too complicated, I'll still use and admire your plugin!  :-)

**Comment by Ekryd** [comment]
I am glad that you enjoy the plugin! And I am sad to say that I cannot fix your issue right now.
I will keep this issue in mind as this plugin continue to grow, and one day your wish may come true :-)
