### ISSUE TITLE
Parsing project and description tags

### ISSUE THREAD

**Issue by akruijff** [Ekryd/sortpom#55]
Hi,

I have just recently start using your plugin. I like it a lot, but there are two things that keep me from using it automatically. First, it also parses the project tag. Second, it parses the description tag. I feel both makes the pom file harder to read.

I know that it is possible to add ignore-sections, but I feel this clutters up the pom file.

Thanks for looking in to this.
Alex

P.S. As an example:
**Project tag**
Given
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
When the parser is run
Then it should not turn the snippet into
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
```

**Tags with long lines.**
Given:
```
<description>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
    vehicula magna in lorem vestibulum lacinia. Nullam quis lobortis purus.
    Etiam ut finibus velit. Donec tempor egestas nisl volutpat pharetra.
</description>
```
When the parser is run
Then it should not turn the snippet into
```
<description>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
    vehicula magna in lorem vestibulum lacinia. Nullam quis lobortis purus.
    Etiam ut finibus velit. Donec tempor egestas nisl volutpat pharetra.</description>
```

**Comment by Ekryd** [comment]
Hi,

I see your two problems and I will look into this as soon as I am able.
Btw. why is the description tag so lengthy?

**Comment by akruijff** [comment]
I didn't make an effort on writing short to the point descriptions for all maven modules. Most only have a name.

I've tried running automatically with a default configuration, but i found that I was limited in what I could do with a individual module. Since, this application was expecting the configuration at a certain location. Putting the configuration on the web solves this of course.

**Comment by Ekryd** [comment]
First problem: Description is put on one line. 

There is an option, in the XML parser that I use, to preserve the content in the elements, but it has a few side-effects.
1. Descriptions like this will not be sorted (since all content is preserved)
```
<description>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
    vehicula magna in lorem vestibulum lacinia. Nullam quis lobortis purus.
  Etiam ut finibus velit. Donec tempor egestas nisl volutpat pharetra.
</description>
```
2. It would affect all elements, even those where you want the content on one line
3. The option keepBlankLines MUST be used, otherwise newlines between elements will be doubled (since the newlines between element are both added by default and also preserved)
4. I dont think that line separators formatting can be trusted anymore. Say that you have a description containing /r/n and specify line separators as /n. That means that the resulting file will have both lines with /r/n and /n

There is also another option to use the ignore sections directive. Example:
```
  <description>
    <?SORTPOM IGNORE?>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse
    vehicula magna in lorem vestibulum lacinia. Nullam quis lobortis purus.
    Etiam ut finibus velit. Donec tempor egestas nisl volutpat pharetra.
    <?SORTPOM RESUME?>
  </description>
```

The content between the ignore directive will not be touched by SortPom at all.


So, can the ignore sections solve your problem for those (few?) cases where the descriptions are long?

**Comment by akruijff** [comment]
Thanks for looking in to this. I did give the SortPom a try. First, I tried it on the custom sortfile, but this didn't work. :( Then, I tried in om the pom file, I felt it cluttered the XML to much. Currently, I use git to reverse some of the effects: `git checkout -p`.

**Comment by Ekryd** [comment]
Second problem: line breaks for project tag

I had a look into the XML parser and unfortunately the methods that print the attributes for an element are private, so I cannot add any custom behaviour to that tag. All output from the Sortpom plugin is built by the XML parser.

It's a pity since I also get annoyed by the long first line.

**Comment by akruijff** [comment]
There is no way that the sort file could be used to indicate how it should deal with each tag?

**Comment by Ekryd** [comment]
The plugin does not modify the original file.
The whole original file is input to the XML parser that creates a new file, so there is nothing left of the original data.
