### ISSUE TITLE
Sortpom Issue: EclipseChe_LSP

### ISSUE THREAD

**Issue by ShivaniBali** [Ekryd/sortpom#59]
I am getting below error on importing pom xml:

The file /Users/shivanibali/CheClone/che/plugins/plugin-mydsl/che-plugin-mydsl-lang-server/pom.xml is not sorted (com.google.code.sortpom:maven-sortpom-plugin:2.3.0:verify:default:validate)

org.apache.maven.plugin.MojoFailureException: The file /Users/shivanibali/CheClone/che/plugins/plugin-mydsl/che-plugin-mydsl-lang-server/pom.xml is not sorted
	at sortpom.exception.ExceptionHandler.throwMojoFailureException(ExceptionHandler.java:16)
	at sortpom.VerifyMojo.sortPom(VerifyMojo.java:187)
	at sortpom.VerifyMojo.execute(VerifyMojo.java:160)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

snippet of pom xml:
<dependency>
      <groupId>com.google.code.sortpom</groupId>
      <artifactId>maven-sortpom-plugin</artifactId>
      <version>${version.sortpom.plugin}</version>
    </dependency>

Attached is the comple xml file, kindly have a look and suggest me a fix.

thanks!
[pom xml.docx](https://github.com/Ekryd/sortpom/files/1715106/pom.xml.docx)

**Comment by Ekryd** [comment]
It seems that you are using the verify goal of the Sortpom plugin, but the pom file that you supplied did not contain the configuration of the sortpom plugin.

Usually the maven build logs contain something like this

[INFO] Verifying file /Users/bjorn/Workspace/SortPom/sorter/pom.xml
**[ERROR] The xml element <groupId> should be placed before <artifactId>**
[ERROR] The file /Users/bjorn/Workspace/SortPom/sorter/pom.xml is not sorted

And if "verifyFail" is set to "Stop", then the build stops.

I suggest that you look at the details of your build log to see if the plugin reports more information.

Otherwise I would need the full maven compile log and the sortpom configuration to determine what happened.
