### ISSUE TITLE
Use sort pom configuration from external maven dependency

### ISSUE THREAD

**Issue by SvenssonWeb** [Ekryd/sortpom#60]
Make it possible to use a resource file from an external dependency instead of having it specified locally.

This would make it possible to use one shared resource (possibly from a BOM project), in all dependent project. Keeping the sorting consistent across projects.

**Comment by camshoff** [comment]
This is already possible using a [Maven extension](https://maven.apache.org/pom.html#Extensions).

All you have to do is to create a small Maven artifact (JAR) that contains the resource, i.e. the custom POM template file, in its root. Since that is a normal Maven artifact, it can be deployed, used across project hierarchies etc.

Let's say this artifact has the Maven coordinates my.group.id:my-sortpom-config:1.0. An extension can than be defined in your project's parent POM like this:
```
  <build>
    <extensions>
      <extension>
        <groupId>my.group.id</groupId>
        <artifactId>my-sortpom-config</artifactId>
        <version>1.0</version>
      </extension>
    </extensions>
    ...
  </build>
```
By defining the artifact as extension, it will be included in the running build's classpath. That means, any plugin has direct access to the contained file, so you can configure sortpom as usual and just specify the name of the POM template that is packaged into the extension.

**Comment by Ekryd** [comment]
@camshoff Your suggestion solves the problem how to distribute the sort order file. Another way to do that is check in the sort order file in a corporate version control system and then refer to the file using an URI.
`<sortOrderFile>https://raw.githubusercontent.com/Ekryd/sortpom/master/sorter/src/main/resources/custom_1.xml</sortOrderFile>`

@SvenssonWeb I guess what you are looking for is a way to store the actual plugin configuration in a central place. Are there any specific parameters that you want to load from such a resource file? 
Do you have an actual example of another maven plugin that have this functionality?

**Comment by SvenssonWeb** [comment]
I think I found a solution using plugin dependencies. 
Looking at your source code I found that you are trying to load the file from the classpath.
Specifying a jar dependency containing a sort config, and then adding the resource path to <sortOrderFile> seams to work. 

I'm not sure if this is stable, but I managed to get it to work in a local environment.

```
<plugin>
    <groupId>com.github.ekryd.sortpom</groupId>
    <artifactId>sortpom-maven-plugin</artifactId>
    <version>2.8.0</version>
    <configuration>
        <sortOrderFile>some.group.id.sortOrder.xml</sortOrderFile>
    </configuration>
    <dependencies>
        <dependency>
            <groupId>some.group.id</groupId>
            <artifactId>sortpom-resource</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by SvenssonWeb** [comment]
@Ekryd Are you talking about storing the plugin configuration specified in a projects pom file? That should be possible to just inherit from a parent pom right? I was thinking more in the line of the `sortOrderFile`, although that might not have been entirely clear in my initial post. Using a URL seams interesting as well, but I try to bring in all dependencies into a project through versioned dependencies in maven to keep a clean structure.

Thanks for you support.

**Comment by Ekryd** [comment]
Working with an additional dependency as you have done is definitely the way to go if you want everything within your Maven repository. I am glad that everything worked out.
