### ISSUE TITLE
sortpom wrongly reports the xml element <artifactId>

### ISSUE THREAD

**Issue by vimal4david** [Ekryd/sortpom#65]
I have a pom file dependency:

```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-web</artifactId>
</dependency>
```

There are no issues reported. But as soon as I add an **exclusions** block to it:

```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-web</artifactId>
  <exclusions>
    <exclusion>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
    </exclusion>
  </exclusions>
</dependency>

```
sortpom complains:

```
--- sortpom-maven-plugin:2.8.0:verify (default) @ project ---
Verifying file /home/user/Repos/project/pom.xml
The xml element <artifactId> should be placed before <groupId>
The file /home/user/Repos/project/pom.xml is not sorted
```

I believe the pom file is actually sorted correctly. I have checked the exclusion [example](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) in the maven official guide and it got  **groupId** placed before the **artifactId**

**sortpom**  doesn't complain about this block
```
<parent>
  <artifactId>spring-boot-starter-parent</artifactId>
  <groupId>org.springframework.boot</groupId>
  <version>2.0.4.RELEASE</version>
  <relativePath></relativePath>
</parent>

```

**Comment by Ekryd** [comment]
Hi,

This is a funny issue. 

The default sort order is taken from the xsd file for the Maven pom file and in that file the order for groupId and artifactId is actually switched for the exclusion element.
Have a look at http://maven.apache.org/xsd/maven-4.0.0.xsd , search for "<xs:complexType name="Exclusion">".

Personally I always use predefinedSortOrder=custom_1, which is consistent.

You could also use predefinedSortOrder=recommended_2008_06 which is the POM Code Convention that was chosen by Maven developers in 2008.  But they have have made some really strange ordering choices like putting organisational information before dependencies, I guess that management overruled actual developers.

What was the problem with the parent block?

I hope that you otherwise enjoy the plugin.

**Comment by vimal4david** [comment]
@Ekryd Thanks for the reply. I am getting the same error for parent POM block as well. But, in the official [guide](https://maven.apache.org/ref/3.5.4/maven-model/maven.html) **groupId** is placed before the **artifactId**

**sortpom** doesn't complain about this block

```
<parent>
  <artifactId>spring-boot-starter-parent</artifactId>
  <groupId>org.springframework.boot</groupId>
  <version>2.0.4.RELEASE</version>
  <relativePath></relativePath>
</parent>
```

**Comment by Ekryd** [comment]
It seems that it has been changed over time. Well spotted, I will start to work with this.

**Comment by vimal4david** [comment]
@Ekryd - Thanks for the prompt fix. The problem is solved.
