### ISSUE TITLE
Recommended configuration phase

### ISSUE THREAD

**Issue by piomar123** [Ekryd/sortpom#77]
On wiki there is the recommended configuration https://github.com/Ekryd/sortpom/wiki/Recommended-configuration:
```xml
<build>
  <plugins>
    <plugin>
      <groupId>com.github.ekryd.sortpom</groupId>
      <artifactId>sortpom-maven-plugin</artifactId>
      <version>2.11.0</version>
      <executions>
        <execution>
          <goals>
            <goal>sort</goal>
          </goals>
          <phase>verify</phase>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```

Shouldn't the `<phase>` be `validate` instead of `verify`? It's also the default phase as seen in the code. 
Does it make sense to compile everything and fail at the end because the POM is not sorted?

**Comment by Ekryd** [comment]
Hi,
Good comment, it really started to make me think. If you use the 'sort' goal, it doesn't fail the build; it just rearranges the pom file. 
So, my original thoughts was that you only want to sort a correct pom-file, otherwise fix the bugs first.

I am quite sure that the pom-file is only read by Maven once when it starts. That means if you sort the pom-file first, before compiling, that the compilation is actually done by the unsorted configuration. This may cause some confusion.

On the other hand. If you use the 'verify' goal to fail a build (e.g. in a CI environment), that check should be most likely be done in the 'validate' phase.

Do you agree?

**Comment by Ekryd** [comment]
Maybe I should add an CI environment section to my documentation...

**Comment by piomar123** [comment]
You are probably right. However, I'm not sure what is the most common usage, but I use only the `verify` goal during `validate` phase in the POM configuration to check if the order is correct.
And in case of violations, I run the `sort` goal manually from a command-line.

This just feel more under control for me than automatic sorting and I can verify that the sorted POM is compiling correctly right away.

**Comment by Ekryd** [comment]
And this is exactly how you would configure it in a Continuous Integration environment (TeamCity, Jenkins etc.). I think that I will add a section about the 'verify' goal. I am a bit busy at the moment, but I will let you know when new documentation is available.

Use sort with verify and verify with validate... makes sense... not :-)

**Comment by Ekryd** [comment]
Hi, I'm back again.
Please have a look at https://github.com/Ekryd/sortpom/wiki/SortPom-and-Build-Servers and tell me what you think.

**Comment by piomar123** [comment]
Looks great 👍
