### ISSUE TITLE
polyglot pom support

### ISSUE THREAD

**Issue by delanym** [Ekryd/sortpom#83]
Support for sorting Ruby DSL poms would be handy. See https://github.com/takari/polyglot-maven

**Comment by Ekryd** [comment]
Wow! I wouldn't even... how... ?

Well, You are welcome to submit a PR :-) 
The SortPom plugin is basically built around an XML parsing library, so not using XML makes it hard to process the files. I think that you basically need a separate parser for each language that you use for Polyglot POMs.

On the other hand I must say that I am impressed with the work with the Polyglot Maven. Do you know if there are any plans for support of compact XML where attributes are used instead of endless element hierarchies?

**Comment by delanym** [comment]
I've seen tickets/comments in the Apache issue tracker about supporting attributes but I don't remember it being very promising. It seems like a separate issue since it would still be XML.

It looks like its not so difficult to support whatever other language - see this Baeldung post on creating a JSON extension https://www.baeldung.com/maven-polyglot

Im as surprised as you are this thing exists. Im wondering why no-one mentioned it in the issue tracker. Clearly Maven's biggest problem is its marketing! There's a bunch of other stuff you might be interested in http://takari.io/book/index.html

I'm no Java developer but my intuition tells me you'd have to sort your collections in the model and let Maven handle the marshalling. The folks over at Takari seem pretty confident about this polyglot thing. Maybe it'll be in Maven 5.

**Comment by Ekryd** [comment]
Well, actually I do not use the internal Maven model. This is a XML sorter/formatter with enhanced schemas for Maven standard. It is not built for other formats.

So unfortunately, no support for this yet.
